### PR TITLE
Add missing tests

### PR DESCRIPTION
**Pull request by Diogo-Rossi**
Add tests required in comment originally posted by @bluebird75 in https://github.com/python-qt-tools/PySide2-stubs/issues/3#issuecomment-1433112384

### CODE REVIEW

**Comment by bluebird75** [comment]
Thanks for the commit. Can you also make the CI green with your additions ? That's the point of the tests ... they should succeed

**Comment by bluebird75** [comment]
Can you rebase on the latest main ? That should make your tests successful

**Comment by Diogo-Rossi** [comment]
> Can you rebase on the latest main ? That should make your tests successful

Done.

Sorry about not investigating the tests. I've been out of time lately.

**Comment by bluebird75** [comment]
I'll merge as it is and fix it afterwards

**Comment by bluebird75** [comment]
Ok, you highlighted a mistake of mine. It took me several days to get the signature of Slot() right so that it typechecks correctly the method arguments and return value. But ... I did my tests on function slots instead of class methods. And it makes a big difference, thanks for highlighting it.

It is now fixed.

**Pull request merged**
